In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [4]:
y=x*3+1

In [5]:
y

array([ 4,  7, 10])

In [6]:
def GD(x,y,epoch):
    w=1
    rate=0.003
    b=1
    for i in range(epoch):
        loss=y-(w*x+b)
        wd=-(2/len(x))*sum(x*(loss))
        bd=-(2/len(x))*sum(loss)
        w-=wd*rate
        b-=bd*rate
        if i%(100)==0:
            print('epoch : ',i,'\tw : ',w,'\t\tb : ',b,'\t\tloss : ',sum(loss**2))
    return w,b

In [7]:
w,b=GD(x,y,3000)

epoch :  0 	w :  1.056 		b :  1.024 		loss :  56
epoch :  100 	w :  2.643605828731269 		b :  1.661197687892923 		loss :  0.26650331188962045
epoch :  200 	w :  2.7176361807783365 		b :  1.6368301342650327 		loss :  0.17531244565437984
epoch :  300 	w :  2.738957972361951 		b :  1.5932387489997009 		loss :  0.15169357478322132
epoch :  400 	w :  2.7571838432255045 		b :  1.5519723976602053 		loss :  0.13131172259179494
epoch :  500 	w :  2.7740865054424417 		b :  1.5135542774188262 		loss :  0.11366848002479799
epoch :  600 	w :  2.789810839072195 		b :  1.4778093610191578 		loss :  0.09839581040944428
epoch :  700 	w :  2.804440648331628 		b :  1.4445523722783973 		loss :  0.0851751998797605
epoch :  800 	w :  2.818052176091977 		b :  1.4136101705121549 		loss :  0.07373093066024297
epoch :  900 	w :  2.8307162999083326 		b :  1.3848216403867852 		loss :  0.06382433083456021
epoch :  1000 	w :  2.8424989620561516 		b :  1.3580368798141338 		loss :  0.05524879680755125
epoch :  1100 	w 

In [8]:
print(w*x+b)

[4.0474101  7.01017416 9.97293823]
